FROM node:21

WORKDIR /frontend

COPY package.json ./
COPY pnpm-lock.yaml ./

RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 3000
RUN ["pnpm", "run", "build"]
CMD ["pnpm", "run", "start"]