version: "3.8"
services:
  db_pg:
    image: postgres:16.1
    environment:
      # Default user is postgres
      POSTGRES_DB: smarthomes
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - pg_data:/var/lib/postgresql/data

  influx:
    image: influxdb:2.7
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: influx
      DOCKER_INFLUXDB_INIT_PASSWORD: influx
      DOCKER_INFLUXDB_INIT_ORG: smarthomes
      DOCKER_INFLUXDB_INIT_BUCKET: smarthomes
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - influx_data:/var/lib/influxdb2

  rabbitmq:
    image: rabbitmq:3
    environment:
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_USER: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  backend_spring:
    depends_on:
      db_pg:
        condition: service_healthy
      influx:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    build: ./backend
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url" : "jdbc:postgresql://db_pg:5432/smarthomes",
          "spring.datasource.username" : "postgres",
          "spring.datasource.password" : "postgres",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
          "spring.jpa.hibernate.ddl-auto" : "update",
          "spring.influx.url" : "https://influx:8086",
          "spring.influx.user" : "influx",
          "spring.influx.password" : "influx",
          "spring.influx.database" : "smarthomes",
          "spring.rabbitmq.host" : "rabbitmq",
          "spring.rabbitmq.port" : "5672",
          "spring.rabbitmq.username" : "rabbitmq",
          "spring.rabbitmq.password" : "rabbitmq",
          "spring.rabbitmq.queue.json.name" : "smarthomes_json",
          "spring.rabbitmq.routing.json.key" : "smarthomes_routing_json_key"

        }'
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./backend:/api
      - maven_data:/root/.m2

  app:
    depends_on:
      - backend_spring
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
      - bun_modules:/frontend/node_modules
    networks:
      - frontend
  
  proxy:
    image: nginx:1.25.3
    ports:
      - 80:80
    depends_on:
      - app
      - backend_spring
    networks:
      - backend
      - frontend
    restart: unless-stopped
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf


volumes:
  bun_modules:
  influx_data:
  maven_data:
  pg_data:


networks:
  backend:
  frontend: