on:
  push:
    branches:
      - main
      - 40-github-actions

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    name: Deploy to DETI machine
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1

      - name: Down containers
        run: docker compose down

      - name: Remove build caches
        run: docker builder prune -a -f

      - name: Up containers
        run: docker compose up --build -d
